/*
 *  linux/arch/i386/kernel/signal.c
 *
 *  Copyright (C) 1991, 1992  Linus Torvalds
 *
 *  1997-11-28  Modified for POSIX.1b signals by Richard Henderson
 *  2000-06-20  Pentium III FXSR, SSE support by Gareth Hughes
 */

#include <linux/sched.h>
#include <linux/mm.h>
#include <linux/smp.h>
#include <linux/smp_lock.h>
#include <linux/kernel.h>
#include <linux/signal.h>
#include <linux/errno.h>
#include <linux/wait.h>
#include <linux/ptrace.h>
#include <linux/unistd.h>
#include <linux/stddef.h>
#include <linux/tty.h>
#include <linux/personality.h>
#include <asm/ucontext.h>
#include <asm/uaccess.h>
#include <asm/i387.h>

#define DEBUG_SIG 0

#define _BLOCKABLE (~(sigmask(SIGKILL) | sigmask(SIGSTOP)))

int FASTCALL(do_signal(struct pt_regs* regs, sigset_t* oldset));

int copy_siginfo_to_user(siginfo_t* to, siginfo_t* from)
{
	if (!access_ok(VERIFY_WRITE, to, sizeof(siginfo_t)))
		return -EFAULT;
	if (from->si_code < 0)
		return __copy_to_user(to, from, sizeof(siginfo_t));
	else {
		int err;

		/* If you change siginfo_t structure, please be sure
		   this code is fixed accordingly.
		   It should never copy any pad contained in the structure
		   to avoid security leaks, but must copy the generic
		   3 ints plus the relevant union member.  */
		err = __put_user(from->si_signo, &to->si_signo);
		err |= __put_user(from->si_errno, &to->si_errno);
		err |= __put_user((short)from->si_code, &to->si_code);
		/* First 32bits of unions are always present.  */
		err |= __put_user(from->si_pid, &to->si_pid);
		switch (from->si_code >> 16) {
		case __SI_FAULT >> 16:
			break;
		case __SI_CHLD >> 16:
			err |= __put_user(from->si_utime, &to->si_utime);
			err |= __put_user(from->si_stime, &to->si_stime);
			err |= __put_user(from->si_status, &to->si_status);
		default:
			err |= __put_user(from->si_uid, &to->si_uid);
			break;
			/* case __SI_RT: This is not generated by the kernel as of now.  */
		}
		return err;
	}
}

/*
 * Atomically swap in the new signal mask, and wait for a signal.
 */
asmlinkage int
sys_sigsuspend(int history0, int history1, old_sigset_t mask)
{
	struct pt_regs* regs = (struct pt_regs*)&history0;
	sigset_t saveset;

	mask &= _BLOCKABLE;
	spin_lock_irq(&current->sigmask_lock);
	saveset = current->blocked;
	siginitset(&current->blocked, mask);
	recalc_sigpending(current);
	spin_unlock_irq(&current->sigmask_lock);

	regs->eax = -EINTR;
	while (1) {
		current->state = TASK_INTERRUPTIBLE;
		schedule();
		if (do_signal(regs, &saveset))
			return -EINTR;
	}
}

asmlinkage int
sys_rt_sigsuspend(sigset_t* unewset, size_t sigsetsize)
{
	struct pt_regs* regs = (struct pt_regs*)&unewset;
	sigset_t saveset, newset;

	/* XXX: Don't preclude handling different sized sigset_t's.  */
	if (sigsetsize != sizeof(sigset_t))
		return -EINVAL;

	if (copy_from_user(&newset, unewset, sizeof(newset)))
		return -EFAULT;
	sigdelsetmask(&newset, ~_BLOCKABLE);

	spin_lock_irq(&current->sigmask_lock);
	saveset = current->blocked;
	current->blocked = newset;
	recalc_sigpending(current);
	spin_unlock_irq(&current->sigmask_lock);

	regs->eax = -EINTR;
	while (1) {
		current->state = TASK_INTERRUPTIBLE;
		schedule();
		if (do_signal(regs, &saveset))
			return -EINTR;
	}
}

asmlinkage int
sys_sigaction(int sig, const struct old_sigaction* act,
	struct old_sigaction* oact)
{
	struct k_sigaction new_ka, old_ka;
	int ret;

	if (act) {
		old_sigset_t mask;
		if (verify_area(VERIFY_READ, act, sizeof(*act)) ||
			__get_user(new_ka.sa.sa_handler, &act->sa_handler) ||
			__get_user(new_ka.sa.sa_restorer, &act->sa_restorer))
			return -EFAULT;
		__get_user(new_ka.sa.sa_flags, &act->sa_flags);
		__get_user(mask, &act->sa_mask);
		siginitset(&new_ka.sa.sa_mask, mask);
	}

	ret = do_sigaction(sig, act ? &new_ka : NULL, oact ? &old_ka : NULL);

	if (!ret && oact) {
		if (verify_area(VERIFY_WRITE, oact, sizeof(*oact)) ||
			__put_user(old_ka.sa.sa_handler, &oact->sa_handler) ||
			__put_user(old_ka.sa.sa_restorer, &oact->sa_restorer))
			return -EFAULT;
		__put_user(old_ka.sa.sa_flags, &oact->sa_flags);
		__put_user(old_ka.sa.sa_mask.sig[0], &oact->sa_mask);
	}

	return ret;
}

asmlinkage int
sys_sigaltstack(const stack_t* uss, stack_t* uoss)
{
	struct pt_regs* regs = (struct pt_regs*)&uss;
	return do_sigaltstack(uss, uoss, regs->esp);
}


/*
 * Do a signal return; undo the signal stack.
 */

struct sigframe
{
	char* pretcode;
	int sig;
	struct sigcontext sc;
	struct _fpstate fpstate;
	unsigned long extramask[_NSIG_WORDS - 1];
	char retcode[8];
};

struct rt_sigframe
{
	char* pretcode;
	int sig;
	struct siginfo* pinfo;
	void* puc;
	struct siginfo info;
	struct ucontext uc;
	struct _fpstate fpstate;
	char retcode[8];
};

static int
restore_sigcontext(struct pt_regs* regs, struct sigcontext* sc, int* peax)
{
	unsigned int err = 0;

#define COPY(x)		err |= __get_user(regs->x, &sc->x)

#define COPY_SEG(seg)							\
	{ unsigned short tmp;						\
	  err |= __get_user(tmp, &sc->seg);				\
	  regs->x##seg = tmp; }

#define COPY_SEG_STRICT(seg)						\
	{ unsigned short tmp;						\
	  err |= __get_user(tmp, &sc->seg);				\
	  regs->x##seg = tmp|3; }

#define GET_SEG(seg)							\
	{ unsigned short tmp;						\
	  err |= __get_user(tmp, &sc->seg);				\
	  loadsegment(seg,tmp); }

	GET_SEG(gs);
	GET_SEG(fs);
	COPY_SEG(es);
	COPY_SEG(ds);
	COPY(edi);
	COPY(esi);
	COPY(ebp);
	COPY(esp);
	COPY(ebx);
	COPY(edx);
	COPY(ecx);
	COPY(eip);
	COPY_SEG_STRICT(cs);
	COPY_SEG_STRICT(ss);

	{
		unsigned int tmpflags;
		err |= __get_user(tmpflags, &sc->eflags);
		regs->eflags = (regs->eflags & ~0x40DD5) | (tmpflags & 0x40DD5);
		regs->orig_eax = -1;		/* disable syscall checks */
	}

	{
		struct _fpstate* buf;
		err |= __get_user(buf, &sc->fpstate);
		if (buf) {
			if (verify_area(VERIFY_READ, buf, sizeof(*buf)))
				goto badframe;
			err |= restore_i387(buf);
		}
	}

	err |= __get_user(*peax, &sc->eax);
	return err;

badframe:
	return 1;
}

/*
 *终止信号处理程序
 *@brief此函数执行一系列操作，最后把被中断的当前进程的硬件上下文拷贝到内核态堆栈，并删除由
 *setup_frame（）建立的帧，以恢复用户态堆栈原来的面貌。当本函数返回时，被中断的当前进程恢复执行。
 */
asmlinkage int sys_sigreturn(unsigned long __unused)
{
	struct pt_regs* regs = (struct pt_regs*)&__unused;
	struct sigframe* frame = (struct sigframe*)(regs->esp - 8);
	sigset_t set;
	int eax;

	if (verify_area(VERIFY_READ, frame, sizeof(*frame)))
		goto badframe;
	if (__get_user(set.sig[0], &frame->sc.oldmask)
		|| (_NSIG_WORDS > 1
			&& __copy_from_user(&set.sig[1], &frame->extramask,
				sizeof(frame->extramask))))
		goto badframe;

	sigdelsetmask(&set, ~_BLOCKABLE);
	spin_lock_irq(&current->sigmask_lock);
	current->blocked = set;
	recalc_sigpending(current);
	spin_unlock_irq(&current->sigmask_lock);

	if (restore_sigcontext(regs, &frame->sc, &eax))
		goto badframe;
	return eax;

badframe:
	force_sig(SIGSEGV, current);
	return 0;
}

asmlinkage int sys_rt_sigreturn(unsigned long __unused)
{
	struct pt_regs* regs = (struct pt_regs*)&__unused;
	struct rt_sigframe* frame = (struct rt_sigframe*)(regs->esp - 4);
	sigset_t set;
	stack_t st;
	int eax;

	if (verify_area(VERIFY_READ, frame, sizeof(*frame)))
		goto badframe;
	if (__copy_from_user(&set, &frame->uc.uc_sigmask, sizeof(set)))
		goto badframe;

	sigdelsetmask(&set, ~_BLOCKABLE);
	spin_lock_irq(&current->sigmask_lock);
	current->blocked = set;
	recalc_sigpending(current);
	spin_unlock_irq(&current->sigmask_lock);

	if (restore_sigcontext(regs, &frame->uc.uc_mcontext, &eax))
		goto badframe;

	if (__copy_from_user(&st, &frame->uc.uc_stack, sizeof(st)))
		goto badframe;
	/* It is more difficult to avoid calling this function than to
	   call it and ignore errors.  */
	do_sigaltstack(&st, NULL, regs->esp);

	return eax;

badframe:
	force_sig(SIGSEGV, current);
	return 0;
}

/*
 * Set up a signal frame.
 */

static int
setup_sigcontext(struct sigcontext* sc, struct _fpstate* fpstate,
	struct pt_regs* regs, unsigned long mask)
{
	int tmp, err = 0;

	tmp = 0;
	__asm__("movl %%gs,%0" : "=r"(tmp) : "0"(tmp));
	err |= __put_user(tmp, (unsigned int*)&sc->gs);
	__asm__("movl %%fs,%0" : "=r"(tmp) : "0"(tmp));
	err |= __put_user(tmp, (unsigned int*)&sc->fs);

	err |= __put_user(regs->xes, (unsigned int*)&sc->es);
	err |= __put_user(regs->xds, (unsigned int*)&sc->ds);
	err |= __put_user(regs->edi, &sc->edi);
	err |= __put_user(regs->esi, &sc->esi);
	err |= __put_user(regs->ebp, &sc->ebp);
	err |= __put_user(regs->esp, &sc->esp);
	err |= __put_user(regs->ebx, &sc->ebx);
	err |= __put_user(regs->edx, &sc->edx);
	err |= __put_user(regs->ecx, &sc->ecx);
	err |= __put_user(regs->eax, &sc->eax);
	err |= __put_user(current->thread.trap_no, &sc->trapno);
	err |= __put_user(current->thread.error_code, &sc->err);
	err |= __put_user(regs->eip, &sc->eip);
	err |= __put_user(regs->xcs, (unsigned int*)&sc->cs);
	err |= __put_user(regs->eflags, &sc->eflags);
	err |= __put_user(regs->esp, &sc->esp_at_signal);
	err |= __put_user(regs->xss, (unsigned int*)&sc->ss);

	tmp = save_i387(fpstate);
	if (tmp < 0)
		err = 1;
	else
		err |= __put_user(tmp ? fpstate : NULL, &sc->fpstate);

	/* non-iBCS2 extensions.. */
	err |= __put_user(mask, &sc->oldmask);
	err |= __put_user(current->thread.cr2, &sc->cr2);

	return err;
}

/*
 * Determine which stack to use..
 */
static inline void*
get_sigframe(struct k_sigaction* ka, struct pt_regs* regs, size_t frame_size)
{
	unsigned long esp;

	/* Default to using normal stack */
	esp = regs->esp;

	/* This is the X/Open sanctioned signal stack switching.  */
	if (ka->sa.sa_flags & SA_ONSTACK) {
		if (sas_ss_flags(esp) == 0)
			esp = current->sas_ss_sp + current->sas_ss_size;
	}

	/* This is the legacy signal stack switching. */
	else if ((regs->xss & 0xffff) != __USER_DS &&
		!(ka->sa.sa_flags & SA_RESTORER) &&
		ka->sa.sa_restorer) {
		esp = (unsigned long)ka->sa.sa_restorer;
	}

	return (void*)((esp - frame_size) & -8ul);
}

static void setup_frame(int sig, struct k_sigaction* ka,
	sigset_t* set, struct pt_regs* regs)
{
	struct sigframe* frame;
	int err = 0;

	frame = get_sigframe(ka, regs, sizeof(*frame));

	if (!access_ok(VERIFY_WRITE, frame, sizeof(*frame)))
		goto give_sigsegv;

	err |= __put_user((current->exec_domain
		&& current->exec_domain->signal_invmap
		&& sig < 32
		? current->exec_domain->signal_invmap[sig]
		: sig),
		&frame->sig);
	if (err)
		goto give_sigsegv;

	err |= setup_sigcontext(&frame->sc, &frame->fpstate, regs, set->sig[0]);
	if (err)
		goto give_sigsegv;

	if (_NSIG_WORDS > 1) {
		err |= __copy_to_user(frame->extramask, &set->sig[1],
			sizeof(frame->extramask));
	}
	if (err)
		goto give_sigsegv;

	/* Set up to return from userspace.  If provided, use a stub
	   already in userspace.  */
	if (ka->sa.sa_flags & SA_RESTORER) {
		err |= __put_user(ka->sa.sa_restorer, &frame->pretcode);
	}
	else {
		err |= __put_user(frame->retcode, &frame->pretcode);
		/* This is popl %eax ; movl $,%eax ; int $0x80 */
		err |= __put_user(0xb858, (short*)(frame->retcode + 0));
		err |= __put_user(__NR_sigreturn, (int*)(frame->retcode + 2));
		err |= __put_user(0x80cd, (short*)(frame->retcode + 6));
	}

	if (err)
		goto give_sigsegv;

	/* Set up registers for signal handler */
	regs->esp = (unsigned long)frame;
	regs->eip = (unsigned long)ka->sa.sa_handler;

	set_fs(USER_DS);
	regs->xds = __USER_DS;
	regs->xes = __USER_DS;
	regs->xss = __USER_DS;
	regs->xcs = __USER_CS;
	regs->eflags &= ~TF_MASK;

#if DEBUG_SIG
	printk("SIG deliver (%s:%d): sp=%p pc=%p ra=%p\n",
		current->comm, current->pid, frame, regs->eip, frame->pretcode);
#endif

	return;

give_sigsegv:
	if (sig == SIGSEGV)
		ka->sa.sa_handler = SIG_DFL;
	force_sig(SIGSEGV, current);
}

static void setup_rt_frame(int sig, struct k_sigaction* ka, siginfo_t* info,
	sigset_t* set, struct pt_regs* regs)
{
	struct rt_sigframe* frame;
	int err = 0;

	frame = get_sigframe(ka, regs, sizeof(*frame));

	if (!access_ok(VERIFY_WRITE, frame, sizeof(*frame)))
		goto give_sigsegv;

	err |= __put_user((current->exec_domain
		&& current->exec_domain->signal_invmap
		&& sig < 32
		? current->exec_domain->signal_invmap[sig]
		: sig),
		&frame->sig);
	err |= __put_user(&frame->info, &frame->pinfo);
	err |= __put_user(&frame->uc, &frame->puc);
	err |= copy_siginfo_to_user(&frame->info, info);
	if (err)
		goto give_sigsegv;

	/* Create the ucontext.  */
	err |= __put_user(0, &frame->uc.uc_flags);
	err |= __put_user(0, &frame->uc.uc_link);
	err |= __put_user(current->sas_ss_sp, &frame->uc.uc_stack.ss_sp);
	err |= __put_user(sas_ss_flags(regs->esp),
		&frame->uc.uc_stack.ss_flags);
	err |= __put_user(current->sas_ss_size, &frame->uc.uc_stack.ss_size);
	err |= setup_sigcontext(&frame->uc.uc_mcontext, &frame->fpstate,
		regs, set->sig[0]);
	err |= __copy_to_user(&frame->uc.uc_sigmask, set, sizeof(*set));
	if (err)
		goto give_sigsegv;

	/* Set up to return from userspace.  If provided, use a stub
	   already in userspace.  */
	if (ka->sa.sa_flags & SA_RESTORER) {
		err |= __put_user(ka->sa.sa_restorer, &frame->pretcode);
	}
	else {
		err |= __put_user(frame->retcode, &frame->pretcode);
		/* This is movl $,%eax ; int $0x80 */
		err |= __put_user(0xb8, (char*)(frame->retcode + 0));
		err |= __put_user(__NR_rt_sigreturn, (int*)(frame->retcode + 1));
		err |= __put_user(0x80cd, (short*)(frame->retcode + 5));
	}

	if (err)
		goto give_sigsegv;

	/* Set up registers for signal handler */
	regs->esp = (unsigned long)frame;
	regs->eip = (unsigned long)ka->sa.sa_handler;

	set_fs(USER_DS);
	regs->xds = __USER_DS;
	regs->xes = __USER_DS;
	regs->xss = __USER_DS;
	regs->xcs = __USER_CS;
	regs->eflags &= ~TF_MASK;

#if DEBUG_SIG
	printk("SIG deliver (%s:%d): sp=%p pc=%p ra=%p\n",
		current->comm, current->pid, frame, regs->eip, frame->pretcode);
#endif

	return;

give_sigsegv:
	if (sig == SIGSEGV)
		ka->sa.sa_handler = SIG_DFL;
	force_sig(SIGSEGV, current);
}

/*
 * OK, we're invoking a handler
 */
 /*
  *@brief捕获一个信号，并激活这个信号的处理程序。
  */
static void
handle_signal(unsigned long sig, struct k_sigaction* ka,
	siginfo_t* info, sigset_t* oldset, struct pt_regs* regs)
{
	/* Are we from a system call? */
	//分析orig_eax域中的非负数，以决定在信号处理程序结束后是否重新执行未完成的系统调用
	if (regs->orig_eax >= 0) {
		/* If so, check system call restarting.. */
		switch (regs->eax) {
		case -ERESTARTNOHAND:
			regs->eax = -EINTR;
			break;

		case -ERESTARTSYS:
			if (!(ka->sa.sa_flags & SA_RESTART)) {
				regs->eax = -EINTR;
				break;
			}
			/* fallthrough */
		case -ERESTARTNOINTR:
			regs->eax = regs->orig_eax;
			regs->eip -= 2;
		}
	}

	/* Set up the stack frame */
	/*如果当前进程有siginfo_t表，就调用setup_rt_frame(），否则就调用setup_frame(）函数；这两个函数都是在用户堆栈的
	顶部创建并填充一个叫做堆栈帧的数据结构。这个堆栈帧里含有信号处理函数返回的地址；还有当前用户进程的被中断的硬件上下文；
	存放用户态进程的浮点寄存器的内容，以及被阻塞的实时信号的位数组和发出sigreturn（）系统调用的可执行代码，当信号处理程序
	结束时执行这段代码。这段代码的指针放在用户堆栈的最顶部。setup_frame（）函数执行时也把这个信号处理程序的地址放入
	保存用户寄存器内容的内核堆栈区的EIP域，当进程又切换到用户态时，立即开始执行信号处理程序。*/
	if (ka->sa.sa_flags & SA_SIGINFO)
		setup_rt_frame(sig, ka, info, oldset, regs);
	else
		setup_frame(sig, ka, oldset, regs);/*由于setup_frame(）的提前操作，在do_signal()返回时，EIP已指向信号处理程序的第一条指令，
											 ESP也指向自己的信息堆栈顶部，此时信号处理程序开始执行*/

											 /*如果设置了SA_ONESHOT标志，说明它的信号处理程序只允许运行一次，因此需要重新设置它的默认操作，
											   以便同一类型的信号再次出现时不再执行这个处理程序。*/
	if (ka->sa.sa_flags & SA_ONESHOT)
		ka->sa.sa_handler = SIG_DFL;
	/*如果没有设置SA_NODEFER标志，这个信号必须在该信号处理程序执行期间阻塞。到此handle_signal()返回到do_signal()。
	之后，do_signal()也立即返回。开始执行信号处理程序。*/
	if (!(ka->sa.sa_flags & SA_NODEFER)) {
		spin_lock_irq(&current->sigmask_lock);
		sigorsets(&current->blocked, &current->blocked, &ka->sa.sa_mask);
		sigaddset(&current->blocked, sig);
		recalc_sigpending(current);
		spin_unlock_irq(&current->sigmask_lock);
	}
}

/*
 * Note that 'init' is a special process: it doesn't get signals it doesn't
 * want to handle. Thus you cannot kill init even with a SIGKILL even by
 * mistake.
 */

 /*
  *@brief内核接收信号的函数。
  *@param segs 栈区的地址，当前进程用户状态下寄存器的内容保存在该栈中。
  *@param oldset 指向sigset_t变量的一个指针
  */
int do_signal(struct pt_regs* regs, sigset_t* oldset)
{
	siginfo_t info;
	struct k_sigaction* ka;

	/*
	 * We want the common case to go fast, which
	 * is why we may in certain cases get here from
	 * kernel mode. Just return without doing anything
	 * if so.
	 */
	 //检查在用户态下运行的进程是否发生了中断，，若没有发生过就什么都不做，只是简单返回。
	if ((regs->xcs & 3) != 3)
		return 1;
	//如果传递的参数oldset位NULL，则用current->blocked域的地址对他进行赋值。
	if (!oldset)
		oldset = &current->blocked;

	/*do_signal这个函数的主题就是这个for循环，退出循环的条件是：所有的
	  非阻塞挂起信号都处理完毕，或至少已处理完一个信号*/
	for (;;) {
		unsigned long signr;

		spin_lock_irq(&current->sigmask_lock);
		signr = dequeue_signal(&current->blocked, &info);/*调用dequeue_signal（）函数获得要处理的非阻塞挂起信号的编号，
														 并把编号值存放在局部变量signr中，如果值为0，说明所有信号已全部被处理，
														 do_signal可以结束，如果为非0值，返回的就是正在等待处理的挂起信号的编号*/
		spin_unlock_irq(&current->sigmask_lock);

		if (!signr)
			break;
		/*如果接收进程正被ptrace系统进程所监视，并且这个信号也不是SIGKILL，do_signal就停止子孙进程的运行，
		  并调用notify_parent（）向祖先进程发送SIGCHLD信号，接着调用调度例程schedule()，给祖先进程一个运行的机会，
		  使祖先进程意识到信号的处理。*/
		if ((current->ptrace & PT_PTRACED) && signr != SIGKILL) {
			/* Let the debugger run.  */
			current->exit_code = signr;
			current->state = TASK_STOPPED;
			notify_parent(current, SIGCHLD);
			schedule();

			/* We're back.  Did the debugger cancel the sig?  */
			if (!(signr = current->exit_code))
				continue;
			current->exit_code = 0;

			/* The debugger continued.  Ignore SIGSTOP.  */
			if (signr == SIGSTOP)
				continue;

			/* Update the siginfo structure.  Is this good?  */
			//如果祖先进程修改了曾经要处理的信号编号，现在do_signal根据新的信息填充info的数据结构
			if (signr != info.si_signo) {
				info.si_signo = signr;
				info.si_errno = 0;
				info.si_code = SI_USER;
				info.si_pid = current->p_pptr->pid;
				info.si_uid = current->p_pptr->uid;
			}

			/* If the (new) signal is now blocked, requeue it.  */
			/*调用sigismember（），检测新的信号是否被屏蔽。若是，就调用send_sig_info（）重新发送或排队。
			  否则，控制流程继续执行下面的代码。*/
			if (sigismember(&current->blocked, signr)) {
				send_sig_info(signr, &info, current);
				continue;
			}
		}

		ka = &current->sig->action[signr - 1];
		if (ka->sa.sa_handler == SIG_IGN) {
			if (signr != SIGCHLD)
				continue;
			/* Check for SIGCHLD: it's special.  */
			while (sys_wait4(-1, NULL, WNOHANG, NULL) > 0)
				/* nothing */;
			continue;
		}
		/*本函数处理一个信号，从struct k_sigaction *ka结构中获取怎样处理这个信号的信息。
		  本函数根据ka变量的内容，可以执行三种信号处理的操作：忽略信号，执行一个默认操作，执行一个指定的信号处理程序。*/
		if (ka->sa.sa_handler == SIG_DFL) {
			int exit_code = signr;

			/* Init gets no signals it doesn't want.  */
			if (current->pid == 1)
				continue;

			switch (signr) {
				//默认操作是ignore的信号如下，对于这些信号的默认操作时不处理，只是继续执行循环。
			case SIGCONT: case SIGCHLD: case SIGWINCH:
				continue;
				/*默认操作时stop的信号如下，对于这些信号的默认操作：一是忽略，二是停止进程运行。如果接收进程所属的进程组没有与TTY连接上，
				那么按照POSIX标准规定，这些基于终端的信号的默认操作是将其忽略。所以函数在这里调用is_orphaned_pgrp()检测当前进程是否与终端相连。
				若没有连接上，就忽略信号，继续执行循环；若连接上，则控制流程继续执行下面的代码。而对信号SIGSTOP的默认操作就是停止进程运行。所以
				上面三个信号到达这里后的默认操作就是停止运行，然后调用notify_parent判断子进程被终止后是否要通知其祖先进程，接着调用schedule()调度，
				当schedule（）重新返回时，则循环继续执行，处理队列中其他的信号。*/
			case SIGTSTP: case SIGTTIN: case SIGTTOU:
				if (is_orphaned_pgrp(current->pgrp))
					continue;
				/* FALLTHRU */
			case SIGSTOP: {
				struct signal_struct* sig;
				current->state = TASK_STOPPED;
				current->exit_code = signr;
				sig = current->p_pptr->sig;
				if (sig && !(sig->action[SIGCHLD - 1].sa.sa_flags & SA_NOCLDSTOP))
					notify_parent(current, SIGCHLD);
				schedule();
				continue;
			}
						/*默认操作是dump的信号为下面6个，对于这些信号的默认操作是在当前进程的目录下调用core_dunp（）生成一个core文件，用于“信息转储”；
						  然后设置标志指明进程在退出之前已生成core文件。接着控制流程执行到default语句，退出循环。信息转储是把这个进程地址空间的内容
						  和寄存器的内容一起保存在这个core文件中，供以后debugger等调试工具来分析使用*/
			case SIGQUIT: case SIGILL: case SIGTRAP:
			case SIGABRT: case SIGFPE: case SIGSEGV:
			case SIGBUS: case SIGSYS: case SIGXCPU: case SIGXFSZ:
				if (do_coredump(signr, regs))
					exit_code |= 0x80;
				/* FALLTHRU */

			default:
				sigaddset(&current->pending.signal, signr);
				recalc_sigpending(current);
				current->flags |= PF_SIGNALED;
				do_exit(exit_code);//终止当前进程的运行，而且do_exit(）永不返回。
				/* NOTREACHED */
			}
		}

		/* Reenable any watchpoints before delivering the
		 * signal to user space. The processor register will
		 * have been cleared if the watchpoint triggered
		 * inside the kernel.
		 */
		__asm__("movl %0,%%db7"	: : "r" (current->thread.debugreg[7]));

		/* Whee!  Actually deliver the signal.  */
		handle_signal(signr, ka, &info, oldset, regs);
		return 1;
	}

	//被中断的系统调用获得重新执行
	/*do_signal()函数在执行for循环时，如果没有取出要处理的信号，将执行break语句退出循环。
	然后它检查orig_eax域中的值，如果该值时正整数，说明曾经有系统调用在其执行过程中被中断，
	do_signal()函数将检查该系统调用被中断的原因（ERESTARTNOHAND，ERESTARTSYS，ERESTARTNOINTR），
	以确定是否需要重新执行被中断的系统调用。如果需要重新执行该系统调用，do_signal()重新
	调整寄存器内容，使EIP指向int 0x80指令，EAX存放系统调用号，从而使该系统调用重新获得执行。*/
	/* Did we come from a system call? */
	if (regs->orig_eax >= 0) {
		/* Restart the system call - no handlers present */
		if (regs->eax == -ERESTARTNOHAND ||
			regs->eax == -ERESTARTSYS ||
			regs->eax == -ERESTARTNOINTR) {
			regs->eax = regs->orig_eax;
			regs->eip -= 2;
		}
	}
	//返回0时，表示它没有处理任何信号。
	return 0;
}
